### ISSUE TITLE
Line input flickers in VHS recording

### ISSUE THREAD

**Issue by linusg** [alimpfard/zigline#22]
I can't perceive any flickering when running the test program in a terminal, but recording it with https://github.com/charmbracelet/vhs results in this:

![zigline-test](https://github.com/user-attachments/assets/3165b76c-bdb5-4425-b15f-a47805e5398e)

To reproduce run `zig build && vhs zigline-test.tape`, using the following tape instructions:

```
Output zigline-test.gif

Type "./zig-out/bin/zigline-test"
Enter
Sleep 1

Type "123456789123456789123456789"
Enter
Sleep 3
```

**Comment by alimpfard** [comment]
Looks like it's due to how zigline clears the buffer (goes down N lines and clears N+M lines up, so it ends up one line above the first line); this is usually not visible because it immediately jumps to the "correct" point, but seems like vhs has the timings for escape sequences exaggerated a lot?
The flicker remains even when zigline stays on the same line at the end:
![zigline-test](https://github.com/user-attachments/assets/6a343f7e-e5fd-4f55-a6b8-656131c3f62e)

**Comment by alimpfard** [comment]
Thanks for boog report, fixed in c2d1ad60050f28c9d158a0d3d2177b2c2a56ba9e :P
![zigline-test](https://github.com/user-attachments/assets/fb2ead5b-359b-4263-a619-7ec66336c039)

**Comment by alimpfard** [comment]
Actually, I broke resetStyle lol

**Comment by alimpfard** [comment]
Okay actually fixed this time

**Comment by linusg** [comment]
Thanks, much appreciated! :tada:

**Comment by linusg** [comment]
Hmm, something still seems off (using 4825f14941762ba52e620ef4caef67e71cf6bedd):

![image](https://github.com/user-attachments/assets/4a014cdb-6353-4aeb-8c64-87113c245b0b)

**Comment by alimpfard** [comment]
🤔 ah, I think the silly span damage detector I wrote is way off
Will fix...hopefully

**Comment by alimpfard** [comment]
I can't really fix the flicker for kiesel that easily, it seems (`"foo` is not highlighted, but `"foo"` is, so it has to redraw everything)
I'll push a fix for the bad rendering, and minimal flickering when those styling "corrections" aren't present, but it'll look vaguely like this at the end:
![kiesel-test](https://github.com/user-attachments/assets/56d0f73e-ad55-4cff-b9e3-446334b457d2)

**Comment by linusg** [comment]
I see - perhaps I could improve things on my end by also tokenizing and highlighting unterminated string literals. Thanks for looking into it!

**Comment by alimpfard** [comment]
To be clear, it _should_ be possible to handle this without redrawing everything (just redraw the bits that have changed), but...that means we have to figure out what changed, which is annoyingly difficult.
